backend:
  name: github
  repo: laespecie/la-especie-web
  branch: main
  auth_endpoint: api/auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Artículos"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "json"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Fecha de Publicación"
        name: "date"
        widget: "datetime"
      - label: "Categorías"
        name: "category"
        widget: "select"
        multiple: true
        options:
          - "Reportajes"
          - "Legislación"
          - "Conservación"
          - "Mascotas"
          - "Tenencia"
          - "Ciencia"
          - "Internacional"
          - "Opinión"
      - label: "Autor"
        name: "author"
        widget: "string"
        default: "La Especie"
      - label: "Imagen Destacada"
        name: "image"
        widget: "image"
        required: false
      - label: "Destacado en Portada Principal"
        name: "featured"
        widget: "boolean"
        default: false
        required: false
      - label: "Resumen (Breve extracto)"
        name: "excerpt"
        widget: "text"
      - label: "Cuerpo de la Noticia"
        name: "body"
        widget: "markdown"

  - name: "obituarios"
    label: "Obituarios (En Memoria)"
    folder: "content/obituarios"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "json"
    fields:
      - label: "Nombre de la Mascota"
        name: "pet_name"
        widget: "string"
      - label: "Años (Ej: 2012 - 2026)"
        name: "years"
        widget: "string"
      - label: "Familia / Remitentes"
        name: "family"
        widget: "string"
      - label: "Fotografía de la Mascota"
        name: "image"
        widget: "image"
      - label: "Epitafio / Mensaje"
        name: "message"
        widget: "text"
